baseURL = 'https://huixiaochen87.github.io/'
languageCode = 'zh-tw'
title = '騙子狗'
theme = 'stack'


[params]
    [params.sidebar.avatar]
        enabled = true
        local = true
        src = "img/avatar.png"